### ISSUE TITLE
What is the License of this material?

### ISSUE THREAD

**Issue by spicedacademy** [pawlodkowski/interactive_climate_map#1]
This is great content that we would like to see integrated in our regular course material. What License is it running on?
At the moment, I cannot ask students to work with the material and publish derived work, because they might be commiting a copyright infringement.

@krother on behalf of Spiced

**Comment by pawlodkowski** [comment]
Good point; I'll reach out to the original owner of the Bokeh tutorial and ask what the licensing / permissions are like.

The other 2 tutorials, Plotly and Folium, were developed ourselves (based on the libraries' own documentation) and so I imagine we could make any license we want for that?

**Comment by krother** [comment]
if it is in a public repo of yours, I assume you wrote the code outside your working hours. So a company has to ask for permission if they want to use/distribute it, because the default is (c) 2020 Paul Wlodkowski. All rights reserved.

**Comment by pawlodkowski** [comment]
MIT License added, along with credits section. Data has also been re-synthesized (based on the original, with random noise added) so we are not publishing real scraped data.
